name: Rsync_deploy
on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.1
      with:
        switches: -avzr --rsync-path=/QOpenSys/pkgs/bin/rsync
        path: dist/
        remote_path: /www/petes/htdocs/petesworkshop/
        remote_host: petesworkshop.com
        remote_user: pete
        remote_key: ${{ secrets.REMOTE_SECRET_KEY }}
